name: CI
on:
  workflow_dispatch:
permissions: {}
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Start SSH session
        uses: luchihoratiu/debug-via-ssh@main
        with:
          NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
          SSH_PASS: ${{ secrets.SSH_PASS }}
      - name: Build
        run: |
          docker build -t wasm-vips .
          docker run --rm -v ${{ github.workspace }}:/src wasm-vips
          tar --exclude=wasm-vips.tar.gz -zcvf wasm-vips.tar.gz -C ${{ github.workspace }}/lib/ .
      - name: "Upload Artifact"
        uses: actions/upload-artifact@v4
        with:
          name: wasm-vips
          path: wasm-vips.tar.gz
          if-no-files-found: error
